Repository discos/simulators, pull requests merged in 2023-06, with the labels that each got.

#328 Fix issue 310
  doc/content/users.rst
  simulators/dbesm/__init__.py
  tests/test_dbesm.py
Labels: feature

#331 Fix #326, improved programTrack behavior
  simulators/minor_servos/__init__.py
  tests/test_minor_servos.py
Labels: enhancement

#334 typos fixed
  simulators/lo/w_LO.py
  simulators/solar_attenuator/__init__.py
  simulators/switch_matrix/__init__.py
  tests/test_lo.py
  tests/test_solar_attenuator.py
  tests/test_switch_matrix.py
Labels: bug, enhancement
