Repository discos/simulators, pull requests merged in 2024-01, with the labels that each got.

#341 Fix #340, reverted changes that caused the issue
  simulators/server.py
Labels: bug

#342 Updated dbesm sim and sim test with getcfg and dbeatt functions
  simulators/dbesm/__init__.py
  tests/test_dbesm.py
Labels: feature

#345 Fix #344, 'raw_unicode_escape' -> 'latin-1'
  simulators/acu/__init__.py
  simulators/gaia/__init__.py
  simulators/server.py
  simulators/totalpower/__init__.py
  simulators/utils.py
Labels: bug, enhancement

#346 Fix #343, server now process chunks of bytes
  .coveragerc
  simulators/acu/__init__.py
  simulators/acu/axis_status.py
  simulators/acu/pointing_status.py
  simulators/gaia/__init__.py
  simulators/minor_servos/__init__.py
  simulators/mscu/__init__.py
  simulators/server.py
  simulators/totalpower/__init__.py
  simulators/utils.py
  tests/test_acu.py
  tests/test_minor_servos.py
  tests/test_server.py
Labels: enhancement
